# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-eks-iam-role
  description: Terraform module to provision an EKS IAM Role for Service Account
  homepage: https://cloudposse.com/accelerate
  topics: ""


